<#
.SYNOPSIS
    Export current session context as a continuation prompt for new chat sessions.

.DESCRIPTION
    Generates a structured .md file in docs/prompts/ that can be used to continue
    work in a new chat window using #file: reference.

.PARAMETER Summary
    Brief summary of current work (required).

.PARAMETER Topic
    Topic identifier for filename (default: "session").

.PARAMETER IncludeGitStatus
    Include current git status in prompt (default: true).

.PARAMETER IncludeIssues
    Include assigned issues in prompt (default: true).

.PARAMETER IncludeRecentCommits
    Include recent commits in prompt (default: true).

.PARAMETER CommitCount
    Number of recent commits to include (default: 5).

.EXAMPLE
    ./scripts/export-session.ps1 -Summary "Implementing LanceDB adapter" -Topic "synapse-lancedb"

.EXAMPLE
    ./scripts/export-session.ps1 -Summary "Bug fix" -Topic "fix-login" -IncludeRecentCommits:$false
#>

param(
    [Parameter(Mandatory=$true, HelpMessage="Brief summary of current work")]
    [string]$Summary,

    [Parameter(HelpMessage="Topic identifier for filename")]
    [string]$Topic = "session",

    [Parameter(HelpMessage="Include git status")]
    [bool]$IncludeGitStatus = $true,

    [Parameter(HelpMessage="Include assigned issues")]
    [bool]$IncludeIssues = $true,

    [Parameter(HelpMessage="Include recent commits")]
    [bool]$IncludeRecentCommits = $true,

    [Parameter(HelpMessage="Number of recent commits")]
    [int]$CommitCount = 5,

    [Parameter(HelpMessage="Additional context to include")]
    [string]$AdditionalContext = ""
)

# Ensure we're in a git repository
if (-not (Test-Path ".git")) {
    Write-Error "Not in a git repository. Run from project root."
    exit 1
}

# Create docs/prompts directory if it doesn't exist
$promptsDir = "docs/prompts"
if (-not (Test-Path $promptsDir)) {
    New-Item -ItemType Directory -Path $promptsDir -Force | Out-Null
    Write-Host "📁 Created $promptsDir directory"
}

# Generate filename
$date = Get-Date -Format "yyyy-MM-dd"
$timestamp = Get-Date -Format "HHmm"
$safeTopic = $Topic -replace '[^a-zA-Z0-9\-]', '-'
$filename = "SESSION_${date}_${safeTopic}.md"
$filepath = Join-Path $promptsDir $filename

# Gather context
$repoName = Split-Path -Leaf (Get-Location)
$branch = git branch --show-current 2>$null
if (-not $branch) { $branch = "unknown" }

# Git status
$gitStatus = ""
if ($IncludeGitStatus) {
    $modified = git status --porcelain 2>$null | Measure-Object | Select-Object -ExpandProperty Count
    $staged = git diff --cached --name-only 2>$null | Measure-Object | Select-Object -ExpandProperty Count
    $gitStatus = @"

## 📊 Git Status

- **Branch:** ``$branch``
- **Modified files:** $modified
- **Staged files:** $staged

"@
}

# Recent commits
$recentCommits = ""
if ($IncludeRecentCommits) {
    $commits = git log --oneline -n $CommitCount 2>$null
    if ($commits) {
        $recentCommits = @"

## 📝 Recent Commits

``````
$commits
``````

"@
    }
}

# Assigned issues
$assignedIssues = ""
if ($IncludeIssues) {
    try {
        $issues = gh issue list --assignee "@me" --state open --limit 10 --json number,title 2>$null | ConvertFrom-Json
        if ($issues -and $issues.Count -gt 0) {
            $issueList = ($issues | ForEach-Object { "- #$($_.number): $($_.title)" }) -join "`n"
            $assignedIssues = @"

## 📋 Assigned Issues

$issueList

"@
        }
    } catch {
        # gh cli not available or not authenticated
        $assignedIssues = ""
    }
}

# Additional context section
$additionalSection = ""
if ($AdditionalContext) {
    $additionalSection = @"

## 📎 Additional Context

$AdditionalContext

"@
}

# Generate the prompt content
$content = @"
---
title: "Session Continuation - $Topic"
type: PROMPT
generated: $date $timestamp
generator: export-session.ps1
project: $repoName
branch: $branch
summary: |
  $Summary
---

# 🔄 Session Continuation Prompt

> **Generated by:** ``export-session.ps1``
> **Delete after use** - This file is temporary context, not permanent documentation.

## 🎯 Session Summary

$Summary
$gitStatus$recentCommits$assignedIssues$additionalSection
## 📋 Instructions for New Session

Continue working on this task. Key points:

1. **Project:** ``$repoName``
2. **Branch:** ``$branch``
3. **Focus:** $Summary

### Immediate Next Steps

Based on the context above, please:
1. Review the current state
2. Continue implementation from where we left off
3. Follow Git-Core Protocol (atomic commits, issue references)

---

*This prompt was auto-generated. Reference it in a new chat with:*
``#file:$filepath``
"@

# Write the file
$content | Out-File -FilePath $filepath -Encoding utf8

# Copy file reference to clipboard
$clipboardText = "#file:$filepath"
$clipboardText | Set-Clipboard

Write-Host ""
Write-Host "✅ Session prompt exported successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📄 File: $filepath" -ForegroundColor Cyan
Write-Host ""
Write-Host "📋 COPIADO AL PORTAPAPELES (Ctrl+V para pegar):" -ForegroundColor Yellow
Write-Host "   $clipboardText" -ForegroundColor White
Write-Host ""
Write-Host "🔄 Para continuar en nueva ventana:" -ForegroundColor Yellow
Write-Host "   1. Abre nueva ventana de chat"
Write-Host "   2. Pega (Ctrl+V) - el texto ya está copiado"
Write-Host "   3. ¡Continúa tu trabajo!"
Write-Host ""
Write-Host "🗑️  Recuerda eliminar el archivo después de usar" -ForegroundColor DarkGray
